spring:
  datasource:
    url: jdbc:mariadb://dbinstance.cveiyepjwzwd.ap-northeast-2.rds.amazonaws.com/main
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  redis:
    port: 6379
    host: 222.111.195.42
logging:
  level:
    com.devpedia.watchapedia.controller: debug
    org.hibernate.SQL: debug