spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 15MB
  cache:
    redis:
      time-to-live: 43200000
    jcache:
      config: classpath:ehcache.xml

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    http-response-body: '{ "status": 429, "code": "C008", "message": "Too many requests" }'
    url: .*
    rate-limits:
    - expression: getRemoteAddr()
      bandwidths:
      - capacity: 5
        time: 1
        unit: seconds

#logging:
#  level:
#    com.devpedia.watchapedia.controller: debug
#    com.devpedia.watchapedia.service: debug
#    org.hibernate.SQL: debug