spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        default_batch_fetch_size: 1000
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 15MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.devpedia.watchapedia.controller: debug
    com.devpedia.watchapedia.service: debug
    org.hibernate.SQL: debug