insert into image values (1, 'jpg', 'poster_image', 'origin_img', '/poster', 1000);

insert into content values ('M', 100, '로맨스/코미디/로맨틱코미디/드라마', 'test description', 'Movie Title1', now(), 1),
                           ('M', 101, '액션/모험/서부극', 'test description', 'Movie Title2', now(), 1),
                           ('M', 102, '모험/범죄/드라마', 'test description', 'Movie Title3', now(), 1),
                           ('M', 103, '로맨스/로맨틱코미디', 'test description', 'Movie Title4', now(), 1),
                           ('M', 104, '범죄/드라마/스릴러/공포', 'test description', 'Movie Title5', now(), 1),
                           ('M', 105, '코미디', 'test description', 'Movie Title6', now(), 1),
                           ('M', 106, '액션/드라마', 'test description', 'Movie Title7', now(), 1),
                           ('M', 107, '액션/모험/드라마/역사/전쟁', 'test description', 'Movie Title8', now(), 1),
                           ('M', 108, 'SF/액션/드라마/판타지', 'test description', 'Movie Title9', now(), 1),
                           ('M', 109, '액션/모험/판타지/스릴러', 'test description', 'Movie Title10', now(), 1),
                           ('B', 200, '소설', 'test description', 'Book Title1', now(), 1),
                           ('B', 201, '', 'test description', 'Book Title2', now(), 1),
                           ('B', 202, '소설/역사', 'test description', 'Book Title3', now(), 1),
                           ('B', 203, '소설', 'test description', 'Book Title4', now(), 1),
                           ('B', 204, '소설', 'test description', 'Book Title5', now(), 1),
                           ('B', 205, '', 'test description', 'Book Title6', now(), 1),
                           ('B', 206, '소설', 'test description', 'Book Title7', now(), 1),
                           ('B', 207, '', 'test description', 'Book Title8', now(), 1),
                           ('B', 208, '', 'test description', 'Book Title9', now(), 1),
                           ('B', 209, '소설/액션', 'test description', 'Book Title10', now(), 1),
                           ('S', 300, '액션/드라마', 'test description', 'TvShow Title1', now(), 1),
                           ('S', 301, '액션/멜로', 'test description', 'TvShow Title2', now(), 1),
                           ('S', 302, '코믹/드라마', 'test description', 'TvShow Title3', now(), 1),
                           ('S', 303, '코믹/멜로', 'test description', 'TvShow Title4', now(), 1),
                           ('S', 304, '액션/드라마', 'test description', 'TvShow Title5', now(), 1),
                           ('S', 305, '액션/멜로', 'test description', 'TvShow Title6', now(), 1),
                           ('S', 306, '코믹/드라마', 'test description', 'TvShow Title7', now(), 1),
                           ('S', 307, '코믹/멜로', 'test description', 'TvShow Title8', now(), 1),
                           ('S', 308, '액션/드라마', 'test description', 'TvShow Title9', now(), 1),
                           ('S', 309, '액션/멜로', 'test description', 'TvShow Title10', now(), 1);

insert into movie values (0.0, 'KR', 'Y', 'Y', 'originTitle1', 100, 1000, 100),
                         (0.0, 'US', 'Y', 'N', 'originTitle2', 100, 1000, 101),
                         (0.0, 'JP', 'N', 'Y', 'originTitle3', 100, 1000, 102),
                         (0.0, 'KR', 'Y', 'Y', 'originTitle4', 100, 1000, 103),
                         (0.0, 'US', 'Y', 'N', 'originTitle5', 100, 1000, 104),
                         (0.0, 'JP', 'N', 'Y', 'originTitle6', 100, 1000, 105),
                         (0.0, 'KR', 'Y', 'Y', 'originTitle7', 100, 1000, 106),
                         (0.0, 'US', 'Y', 'N', 'originTitle8', 100, 1000, 107),
                         (0.0, 'JP', 'N', 'Y', 'originTitle9', 100, 1000, 108),
                         (0.0, 'KR', 'Y', 'Y', 'originTitle10', 100, 1000, 109);

insert into book values ('목차', '제작사 설명', 500, '부제1', 200),
                        ('목차', '제작사 설명', 500, '부제2', 201),
                        ('목차', '제작사 설명', 500, '부제3', 202),
                        ('목차', '제작사 설명', 500, '부제4', 203),
                        ('목차', '제작사 설명', 500, '부제5', 204),
                        ('목차', '제작사 설명', 500, '부제6', 205),
                        ('목차', '제작사 설명', 500, '부제7', 206),
                        ('목차', '제작사 설명', 500, '부제8', 207),
                        ('목차', '제작사 설명', 500, '부제9', 208),
                        ('목차', '제작사 설명', 500, '부제10', 209);

insert into tv_show values ('KR', 'Y', 'Y', 'originTitle1', 300),
                           ('KR', 'Y', 'Y', 'originTitle2', 301),
                           ('KR', 'Y', 'Y', 'originTitle3', 302),
                           ('KR', 'Y', 'Y', 'originTitle4', 303),
                           ('KR', 'Y', 'Y', 'originTitle5', 304),
                           ('KR', 'Y', 'Y', 'originTitle6', 305),
                           ('KR', 'Y', 'Y', 'originTitle7', 306),
                           ('KR', 'Y', 'Y', 'originTitle8', 307),
                           ('KR', 'Y', 'Y', 'originTitle9', 308),
                           ('KR', 'Y', 'Y', 'originTitle10', 309);